### ISSUE TITLE
TODO in case of acceptance

### ISSUE THREAD

**Issue by nicobonne** [polimi-ispl/prnu-anonymization-detector#1]
On branch release:
- [ ] Remove hardcoded project root path in params.py
- [ ] Create minimal testing dataset (12 images per class)
- [ ] Create minimal db.csv
- [ ] Pick best resnet model and put it in data/model/
- [ ] Remove unused database class in db_classes.py
- [ ] Create demo testing script
- [ ] Release branch
